from typing import Protocol

class IProjectRepository(Protocol):
    def create(self, name: str, description: str = "") -> Project: ...
    def get_by_name(self, name: str): ...
    def delete(self, name: str): ...
    def list(self): ...

class ITaskRepository(Protocol):
    def add(self, project_id: int, name: str, description: str = "", deadline=None): ...
    def get(self, project_id: int, name: str): ...
    def list_overdue(self, now_date): ...
    # etc.
